version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - qdrant
      - minio

  celery-worker:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - minio
    command: celery -A app.workers.celery_app worker --loglevel=info --concurrency=2 -Q document_conversion,vector_indexing,celery

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db

  redis:
    image: redis:6.2-alpine

  qdrant:
    image: qdrant/qdrant:v1.8.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  qdrant_storage:
  minio_storage: 