"""add_chat_models

Revision ID: 19980b5ea2b0
Revises: 7f92e80a9586
Create Date: 2025-06-09 05:13:39.074413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19980b5ea2b0'
down_revision = '7f92e80a9586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 