"""Add vector indexing fields to document model

Revision ID: bf2a7c849a1b
Revises: af3a7a696a8a
Create Date: 2025-06-08 15:50:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf2a7c849a1b'
down_revision = 'af3a7a696a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('indexing_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('chunks_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('vectors_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'vectors_count')
    op.drop_column('documents', 'chunks_count')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'indexing_metadata')
    # ### end Alembic commands ### 