"""fix_chat_metadata_column_names

Revision ID: b1563f032a4a
Revises: 19980b5ea2b0
Create Date: 2025-06-09 05:15:02.553238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1563f032a4a'
down_revision = '19980b5ea2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 