apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: smart-ebook-chat
  labels:
    app.kubernetes.io/name: smart-ebook-chat-system
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: "smart_ebook_user"
  POSTGRES_PASSWORD: "CHANGE_THIS_PASSWORD_IN_PRODUCTION"
  DATABASE_URL: "postgresql://smart_ebook_user:CHANGE_THIS_PASSWORD_IN_PRODUCTION@postgresql:5432/smart_ebook_chat"

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: smart-ebook-chat
  labels:
    app.kubernetes.io/name: smart-ebook-chat-system
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  JWT_SECRET_KEY: "CHANGE_THIS_JWT_SECRET_KEY_IN_PRODUCTION"
  SECRET_KEY: "CHANGE_THIS_APPLICATION_SECRET_KEY_IN_PRODUCTION"

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: smart-ebook-chat
  labels:
    app.kubernetes.io/name: smart-ebook-chat-system
    app.kubernetes.io/component: storage
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "CHANGE_THIS_MINIO_ACCESS_KEY"
  MINIO_SECRET_KEY: "CHANGE_THIS_MINIO_SECRET_KEY"

---
apiVersion: v1
kind: Secret
metadata:
  name: llm-api-secrets
  namespace: smart-ebook-chat
  labels:
    app.kubernetes.io/name: smart-ebook-chat-system
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  GOOGLE_API_KEY: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: smart-ebook-chat
  labels:
    app.kubernetes.io/name: smart-ebook-chat-system
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  REDIS_PASSWORD: "CHANGE_THIS_REDIS_PASSWORD"
  REDIS_URL: "redis://:CHANGE_THIS_REDIS_PASSWORD@redis:6379/0"
  CELERY_BROKER_URL: "redis://:CHANGE_THIS_REDIS_PASSWORD@redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://:CHANGE_THIS_REDIS_PASSWORD@redis:6379/0"

---
apiVersion: v1
kind: Secret
metadata:
  name: qdrant-secrets
  namespace: smart-ebook-chat
  labels:
    app.kubernetes.io/name: smart-ebook-chat-system
    app.kubernetes.io/component: vector-db
type: Opaque
stringData:
  QDRANT_API_KEY: "CHANGE_THIS_QDRANT_API_KEY"
  QDRANT_URL: "http://qdrant:6333" 